parameters:
- name: subTaskKey
  type: string
  default: ''

steps:
- script: |
    echo $pwd
    tar -czvf $(resource)-generated.tar.gz $(resource)
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob upload -c dcblob -f $(resource)-generated.tar.gz -n $(resource)-generated.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
  condition: and(always(), ne(variables['ValidationResult'], ''))
  displayName: 'After $(TASK_KEY)'