steps:   
- task: ManualValidation@0
  # task times out in 1 day
  timeoutInMinutes: 1440
  inputs:
    notifyUsers: |
      chunyu@microsoft.com
      yuchun_green@hotmail.com
    instructions: 'Please validate the build configuration and resume'
    onTimeout: 'resume'