steps:
- template: VariableSetTask.yml
- script: |
    echo $pwd
    mkdir -p generated/$(ResourceProvider)
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob download -c depthcoverage -f $(TARGET)-$(ResourceProvider)-generated.tar.gz -n $(TARGET)-$(ResourceProvider)-generated.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
    tar -xzvf $(TARGET)-$(ResourceProvider)-generated.tar.gz
    tar -czvf $(TARGET)-$(ResourceProvider)-generated.tar.gz generated/$(ResourceProvider)
    ls -l generated/
  displayName: 'Before $(TASK_KEY)'