steps:
- bash: |
    echo "https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com" > ~/.git-credentials
    git clone --branch depth-$(TARGET)-$(ResourceProvider) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com/$(Swagger_ORG)/azure-rest-api-specs.git
    sdktarget=$(TARGET)
    if [ "$sdktarget" == "terraform" ]; then
      git clone --branch depth-$(TARGET)-$(ResourceProvider) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com/$(TF_ORG)/terraform-provider-azurerm.git
      cd ./terraform-provider-azurerm
      tf_existed_in_remote=$(git ls-remote --heads origin depth-code-$(TARGET)-$(ResourceProvider))
      if [[ -z ${tf_existed_in_remote} ]]; then
        git checkout -b depth-code-$(TARGET)-$(ResourceProvider)
      else
        git checkout depth-code-$(TARGET)-$(ResourceProvider)
        git reset --hard origin/depth-$(TARGET)-$(ResourceProvider)
      fi
      cp ../azure-rest-api-specs/specification/$(ResourceProvider)/resource-manager/readme.terraform.md ./azurerm/internal/services/$(ResourceProvider)/
    fi

    if [ "$sdktarget" == "clicore" ] || [ "$sdktarget" == "cliextension" ]; then
      git clone --branch depth-$(TARGET)-$(ResourceProvider) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com/$(CLI_ORG)/azure-cli
      name=$(ResourceProvider)
      if [ "$name" == "compute" ]; then 
        name="vm"
      fi
        
      cd ./azure-cli

      tf_existed_in_remote=$(git ls-remote --heads origin depth-code-$(TARGET)-$(ResourceProvider))
      if [[ -z ${tf_existed_in_remote} ]]; then
        git checkout -b depth-code-$(TARGET)-$(ResourceProvider)
      else
        git checkout depth-code-$(TARGET)-$(ResourceProvider)
        git reset --hard origin/depth-$(TARGET)-$(ResourceProvider)
      fi
      cp ../azure-rest-api-specs/specification/$(ResourceProvider)/resource-manager/readme.az.md ./
      git branch; git add -A; git commit -m "autogenerated"; git push -f origin depth-code-$(TARGET)-$(ResourceProvider);

    fi
    
    git config credential.helper store; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
    git branch; git add -A; git commit -m "autogenerated"; git push origin depth-code-$(TARGET)-$(ResourceProvider);

    cd $(Pipeline.Workspace)/s
    
    sdktarget=$(TARGET)
    org=""
    repo=""
    base="master"
    sdk="";
    to_mail="";
    cc_mail=$(CCEails);
    if [ "$sdktarget" == "terraform" ]; then
        org=$(TF_ORG)
        repo="terraform-provider-azurerm"
        sdk="terraform"
        to_mail="tfazengvsc@microsoft.com;chunyu@microsoft.com;vsccodegen@microsoft.com"
    else
        org=$(CLI_ORG)
        repo="azure-cli"
        base="dev"
        sdk="clicore"
        to_mail="AzCLIInternal@microsoft.com;chunyu@microsoft.com;vsccodegen@microsoft.com"
    fi
    
    codePR=$(curl -X POST -H "Content-Type: application/json" http://$(CodegenApp_Server)/DepthCoverage/generateCodePR -d '{"token":"$(PIPELINE_TOKEN)", "org":"'"$org"'", "repo":"'"$repo"'", "title":"{depth coverage, not merge} pull request of $(ResourceProvider)", "branch":"depth-code-$(TARGET)-$(ResourceProvider)", "base":"'"$base"'"}')
    # echo $codePR
    echo "##vso[task.setvariable variable=CODE_PULLREQUEST]$codePR"
  displayName: "Generate Code Pull Request"