steps:
- script: |
    git clone --branch pipeline https://github.com/microsoft/terraform-provider-azurerm.git
    git clone https://github.com/Azure/azure-rest-api-specs.git
    git config credential.helper store ; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
  displayName: 'pull repo'
- script: |
    npm install -g metadata-tool
    metadata-tool $(README_FILE)
  displayName: 'Generate Trenton readme file'
- script: |
    npm install -g autorest && npm install -g typescrip
  displayName: 'install autorest'
- script: |
    echo $pwd
    autorest --version=3.0.6219 --trenton --use=https://trenton.blob.core.windows.net/trenton/autorest-trenton-latest.tgz --trenton-output-folder=./ $(README_FILE_PATH)
  displayName: 'Generate TF'