steps:
- script: |
    sdktarget=$(TARGET)
    if [ "$sdktarget" == "TF" ]; then
      git clone --branch pipeline https://github.com/microsoft/terraform-provider-azurerm.git
    fi

    if [ "$sdktarget" == "CLI-core" ] || [ "$sdktarget" == "CLI-extension" ]; then
      git clone https://github.com/Azure/azure-cli
    fi
    git clone https://github.com/Azure/azure-rest-api-specs.git
    # cd ./azure-rest-api-specs
    # git checkout -b $(TARGET)$(ResourceProvider)
    # git config credential.helper store ; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
    
  displayName: 'pull repo'
- script: |
    sudo npm install -g autorest@latest && sudo npm install -g typescript
  displayName: 'install autorest'
- script: |
    echo "$README_FILE"
    sdktarget=$(TARGET)
    if [ "$sdktarget" == "TF" ]; then
      echo 'workOnTF'
      sudo npm install -g metadata-tool
      metadata-tool ./azure-rest-api-specs/$(README_FILE)
    fi

    if [ "$sdktarget" == "CLI-core" ] || [ "$sdktarget" == "CLI-extension" ]; then
      echo 'workonCLI'
      sudo npm install -g depthcoverage --unsafe-perm=true --allow-root
      sudo npm install -g autorest-autoconfig
      depthcoverage --token=$(PIPELINE_TOKEN) --org=$(PIPELINE_ORG) --repo=$(PIPELINE_REPO) --operation=readPR --PRNumber=27
      ls -l
      autorest --use=autorest-autoconfig@latest ./azure-rest-api-specs/$(README_FILE) --resource-file=./$(RESOURCE_MAP_FILE)
      ls -l ./azure-rest-api-specs/specification/$(ResourceProvider)/resource-manager

      echo "https://$(PIPELINE_USER):${PIPELINE_TOKEN}@github.com" > ~/.git-credentials
      # cd ./azure-rest-api-specs
      # git config credential.helper store ; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
      # git checkout -b $(TARGET)$(ResourceProvider); git branch; git pull origin $(TARGET)$(ResourceProvider); git add -A; git commit -m "autogenerated"; git push origin $(TARGET)$(ResourceProvider);
    fi
  displayName: 'Generate or update configuration file'
- bash: |
    echo $pwd
    pwd
    sdktarget=$(TARGET)
    if [ "$sdktarget" == "TF" ]; then
      echo "start tf code"
      mkdir generated
      autorest --version=3.0.6219 --trenton --use=https://trenton.blob.core.windows.net/trenton/autorest-trenton-latest.tgz --generate-extra-acctest=true --trenton-output-folder=./generated ./azure-rest-api-specs/$(README_FILE)
      ls -l generated/$(ResourceProvider)
      if [ "$?" != "0" ]; then
        echo -e "\e[31m[$(date -u)] ERROR: [$OPERATION : $(ResourceProvider)]: Generate code failed"
        exit 1
      fi
    fi

    if [ "$sdktarget" == "CLI-core" ] || [ "$sdktarget" == "CLI-extension" ]; then
      cat ./azure-rest-api-specs/specification/$(ResourceProvider)/resource-manager/readme.az.md
      echo "end cat" 
      autorest --az --use=@autorest/az@latest ./azure-rest-api-specs/$(README_FILE) --azure-cli-folder=./azure-cli  --target-mode=core
    fi
  displayName: 'Generate code'