steps:
- script: |
    git clone --branch pipeline https://github.com/microsoft/terraform-provider-azurerm.git
    git clone https://github.com/Azure/azure-rest-api-specs.git
    git config credential.helper store ; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
  displayName: 'pull repo'
- script: |
    echo $(README_FILE)
    sudo npm install -g metadata-tool
    metadata-tool ./azure-rest-api-specs/$(README_FILE)
  displayName: 'Generate Trenton readme file'
- script: |
    sudo npm install -g autorest && sudo npm install -g typescript
  displayName: 'install autorest'
- script: |
    echo $pwd
    mkdir generated
    autorest --version=3.0.6219 --trenton --use=https://trenton.blob.core.windows.net/trenton/autorest-trenton-latest.tgz --trenton-output-folder=./generated ./azure-rest-api-specs/$(README_FILE)
    if [ "$?" != "0" ]; then
      echo -e "\e[31m[$(date -u)] ERROR: [$OPERATION : $RP]: Generate code failed"
      exit 1
    fi
  displayName: 'Generate TF'