steps:
- script: |
    echo $(TARGET)
    if [ '$(TRAGET)' == 'TF' ]; then
      git clone --branch pipeline https://github.com/microsoft/terraform-provider-azurerm.git
    fi

    if [ '$(TARGET)' == 'CLI-core' ] || [ '$(TARGET)' == 'CLI-extension' ]; then
      git clone https://github.com/Azure/azure-cli
    fi
    git clone https://github.com/Azure/azure-rest-api-specs.git
    git config credential.helper store ; git config --global user.email "chunyu@microsoft.com";git config --global user.name "chunyu3;"
  displayName: 'pull repo'
- script: |
    sudo npm install -g autorest && sudo npm install -g typescript
  displayName: 'install autorest'
- script: |
    echo $(README_FILE)
    if [ '$(TRAGET)' == 'TF' ]; then
      sudo npm install -g metadata-tool
      metadata-tool ./azure-rest-api-specs/$(README_FILE)
    fi

    if [ '$(TARGET)' == 'CLI-core' ] || [ '$(TARGET)' == 'CLI-extension' ]; then
      sudo npm install -g az-depth-coverage --unsafe-perm=true --allow-root
      sudo npm install -g autorest-autoconfig
      depthcoverage --token=$(PIPELINE_TOKEN) --org=$(PIPELINE_ORG) --repo=$(PIPELINE_REPO) --operation=readPR --PRNumber=6
      autorest --use=autorest-autoconfig@latest ./azure-rest-api-specs/$(README_FILE) --resource-file=${{variables.RESOURCE_MAP_FILE}}
    fi
  displayName: 'Generate or update configuration file'
- script: |
    echo $pwd
    if [ '$(TRAGET)' == 'TF' ]; then
      mkdir generated
      autorest --version=3.0.6219 --trenton --use=https://trenton.blob.core.windows.net/trenton/autorest-trenton-latest.tgz --trenton-output-folder=./generated ./azure-rest-api-specs/$(README_FILE)
      ls -l generated/$(ResourceProvider)
      if [ "$?" != "0" ]; then
        echo -e "\e[31m[$(date -u)] ERROR: [$OPERATION : $RP]: Generate code failed"
        exit 1
      fi
    fi

    if [ '$(TARGET)' == 'CLI-core' ] || [ '$(TARGET)' == 'CLI-extension' ]; then
      autorest --az --use=@autorest/az@latest ./azure-rest-api-specs/$(README_FILE) --azure-cli-folder=./azure-cli   --target-mode=core 
    fi
  displayName: 'Generate code'