steps:
- template: .azure-pipelines/templates/GenerateCodePR.yml
- bash: |
    logurl="https://depthcoverage.blob.core.windows.net/depthcoverage/log/$(TARGET)-$(ResourceProvider)-$(Build.BuildId)-$(TASK_KEY).log"
    codePR=$(CODE_PULLREQUEST)
    triggerPR="https://github.com/${PIPELINE_ORG}/depth-coverage-pipeline/pull/$(System.PullRequest.PullRequestNumber)"
    resolveURL="http://$(CodegenApp_Server):$(CodegenApp_Port)/DepthCoverage/Resolve"
        
    python scripts/issueResolve.py "Onboarding" "Please Reolve issues when Onboard '$(ResourceProvider)'" "$logurl" "$codePR" "$triggerPR" "$resolveURL" > scripts/email.html
    # cat scripts/email.html
    to_mail="$(Contactors)"
        
    sudo pip install wheel
    sudo pip install sendgrid
    python scripts/sendGridemail.py "scripts/email.html" $to_mail "Depth-coverage Issue Resolve" $(API_KEY)
  displayName: 'Alert issue'
  condition: failed()