steps:
- bash: |
    pwd
    . venv/bin/activate
    which azdev
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    # az vm show --name MyVm --resource-group MyResourceGroup --debug
    azdev test vm --live --discover --no-exitfirst 1>clilivetest.log 2>&1
    if [ "$?" != "0" ]; then
      echo -e "\e[31m[$(date -u)] ERROR: [$(ResourceProvider)]: CLI Test failed"
      az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
      az storage blob upload -c depthcoverage -f clilivetest.log -n log/$(TARGET)-$(ResourceProvider)-$(Build.BuildId)-clilivetest.log --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
      exit 1
    fi
  displayName: 'CLI Test'