steps:
- bash: |
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    git clone https://github.com/Azure/avs.git
    cd avs
    npm install
    . initiate.sh
    tsc
    sudo node dist/src/main.js > ../mockserver.log &
    cd $(Pipeline.Workspace)/s
    ls -l
    ls -l avs/dist
    ls -l ./venv/lib/
    ls -l ./venv/lib/python*/site-packages/certifi/cacert.pem
    cat scripts/config/localhost_ca.crt >> ./venv/lib/python*/site-packages/certifi/cacert.pem
    ls -l ./venv/lib/python*/site-packages/certifi/cacert.pem
    . venv/bin/activate
    which python
    export AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1
    az --version
    az cloud register -n virtualCloud --endpoint-resource-manager "https://localhost:8443"
    az cloud set -n virtualCloud
    sleep 3m
  displayName: 'setup cli mock env'